version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - "postgres"
      - "postgres:postgres"
    env_file:
      - ./server/.env

    container_name: server
  
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bookings
    ports:
      - 5432:5432
    volumes: 
      - postgres:/var/lib/postgresql/data
  
  client:
    build: ./dashboard
    ports:
    - "3000:3000"
    container_name: dashboard
    


volumes:
  postgres:
    name: postgres
