


POST ${process.env.HOST}/server/event/create HTTP/1.1
Content-Type: application/json

{
  "title": "ERS",
  "category": "Club-Show",
  "tags": "car, car",
  "description": "asdasdasd",
  "date": "\"2024-01-17T13:54:37.024Z\"",
  "time": "12:00 AM",
  "venue": "Blore",
  "artist": "Saif",
  "terms": "asdasdas"
}

###
POST ${process.env.HOST}/server/event/razorpay-payment


###

GET ${process.env.HOST}/server/event HTTP/1.1

###
GET ${process.env.HOST}/server/event/get-user/saifkhan501721@gmail.com

###

GET ${process.env.HOST}/server/event/0d224ba7-2bf2-4a37-8502-4a15e447cce1 HTTP/1.1

###

GET ${process.env.HOST}/server/event/tickets/b1fc12c3-b519-4fc7-82de-2441568131dc HTTP/1.1
###

POST ${process.env.HOST}/server/event/ticket/create HTTP/1.1
Content-Type: application/json

[
  {
    "eventid": "6639bee8-e590-4d49-a144-85b0b2b59ba5",
    "type": "Club-Show",
    "amt": 320,
    "qty": 200,
    "description": "asdasd"
},
{
    "eventid": "6639bee8-e590-4d49-a144-85b0b2b59ba5",
    "type": "Club-Show",
    "amt": 320,
    "qty": 200,
    "description": "asdasd"
}
]

###
POST ${process.env.HOST}/server/event/order/post HTTP/1.1
Content-Type: application/json

[
{
  "eventid": "3e41f896-6f62-4787-bda8-51396b05bb77",
  "amt": 50,
  "tickets": 1,
  "ticketid": "9eb7a5d4-a6a3-4594-9689-3b3fa9d23447",
  "email": "saifkp517@gmail.com",
  "type": "General - Female",
  "organizer": "ers"
},
{
  "eventid": "3e41f896-6f62-4787-bda8-51396b05bb77",
  "amt": 50,
  "tickets": 1,
  "ticketid": "9eb7a5d4-a6a3-4594-9689-3b3fa9d23447",
  "email": "saifkp517@gmail.com",
  "type": "General - Female",
  "organizer": "ers"
},
{
  "eventid": "3e41f896-6f62-4787-bda8-51396b05bb77",
  "amt": 50,
  "tickets": 1,
  "ticketid": "9eb7a5d4-a6a3-4594-9689-3b3fa9d23447",
  "email": "saifkp517@gmail.com",
  "type": "General - Female",
  "organizer": "ers"
}
]


###

POST ${process.env.HOST}/server/event/verify-otp HTTP/1.1
Content-Type: application/json

{
  "otp": "1303",
  "pageid": "a75e2ed7-e684-4a1a-9b68-f52adddf0352"
}

###

post ${process.env.HOST}/server/event/sendOTP
Content-Type: application/json

{
  "otp": "ljsdhfslkfdhlsfjsdjfdsfskjhfs",
  "email": "saifkp517@gmail.com"
}