


POST http://localhost:8080/event/create HTTP/1.1
Content-Type: application/json

{
  "title": "ERS",
  "category": "Club-Show",
  "tags": "car, car",
  "description": "asdasdasd",
  "date": "\"2024-01-17T13:54:37.024Z\"",
  "time": "12:00 AM",
  "venue": "Blore",
  "artist": "Saif",
  "terms": "asdasdas"
}

###
POST http://localhost:8080/event/razorpay-payment


###

GET http://localhost:8080/event HTTP/1.1

###
GET http://localhost:8080/event/get-user/saifkhan501721@gmail.com

###

GET http://localhost:8080/event/0d224ba7-2bf2-4a37-8502-4a15e447cce1 HTTP/1.1

###

GET http://localhost:8080/event/tickets/9672628d-2b20-451a-aba3-8bfa3442e0c1 HTTP/1.1
###

POST http://localhost:8080/event/ticket/create HTTP/1.1
Content-Type: application/json

{
    "eventid": "09de69b1-69e3-46ea-b655-fb3c23604035",
    "type": "Club-Show",
    "price": 320,
    "qty": 200,
    "description": "asdasd"
}

###
POST http://localhost:8080/event/order/post HTTP/1.1
Content-Type: application/json

{
    "eventid": "8e556887-45d1-4f63-824e-4d49aa3cacec",
    "ticketid": "d5108e4c-a276-4e0b-807d-12cb84fe2541",
    "amt": 640,
    "tickets": 20,
    "email": "saifkhan501721@gmail.com",
    "type": "VIP"
}

###

POST http://localhost:8080/event/verify-otp HTTP/1.1
Content-Type: application/json

{
  "otp": "234234",
  "pageid": "324234234234"
}

###

post http://localhost:8080/event/sendOTP
Content-Type: application/json

{
  "otp": "ljsdhfslkfdhlsfjsdjfdsfskjhfs",
  "email": "saifkp517@gmail.com"
}